# Generated by Django 3.1.6 on 2021-03-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerID', models.IntegerField()),
                ('ChannelID', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='PaymentDue',
            field=models.IntegerField(),
        ),
    ]
