# Generated by Django 3.1.7 on 2021-03-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210319_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='PaymentDue',
        ),
        migrations.RemoveField(
            model_name='user',
            name='VIP',
        ),
    ]
