# Generated by Django 3.1.6 on 2021-03-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210321_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.TextField()),
                ('TxID', models.TextField()),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Coins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
